# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# strategy:
#   matrix:
#     linux:
#       imageName: "ubuntu-latest"
#     mac:
#       imageName: "macos-10.13"
#     windows:
#       imageName: "vs2017-win2016"
#   maxParallel: 3

# pool:
#   vmImage: $(imageName)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

  steps:
# #################################3  R U N   Y O U R   T E S T S  ##########################
steps:
# ...
# do this after your tests have run
- script: dotnet test unitTest --logger trx
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    arguments: '--configuration $(buildConfiguration)'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'


# steps:
# - script: echo Hello, world!
#  displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

#######    Publish Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    testRunTitle: 'API Automation_05272019'